### ISSUE TITLE
Gradle task bootRun must be restarted for Java changes to take effect

### ISSUE THREAD

**Issue by haba713** [vaadin/base-starter-spring-gradle#106]
When changing the Java code, the Gradle task must be restarted for the change to be visible in a browser.

Steps for reproducing the issue:
1. `git clone git@github.com:vaadin/base-starter-spring-gradle.git`
2. `cd base-starter-spring-gradle/`
3. `./gradlew clean bootRun`
4. See the field label "Your name" in http://localhost:8080/
5. Change the field label in `MainView.java`: `new TextField("Your name")` → `new TextField("Her name")`
6. Wait for 10 seconds.
7. Reload the browser page http://localhost:8080/
8. **The issue:** The text label has not changed to "Her name".
9. Terminate the Gradle task: `Ctrl-C`
10. `./gradlew clean bootRun`
11. Reload the browser page http://localhost:8080/
12. See the field label "Her name" in http://localhost:8080/

Environment:
- java: OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb11u1, mixed mode, sharing)
- os: Debian 11 (Bullseye)

**Comment by haba713** [comment]
This is the wrong way to run the application. It should be run as a Java application in IDE. not as a Gradle task. README.md is misleading (`./gradlew clean bootRun`) and outdated (`v14`).

**Comment by simasch** [comment]
No. Everything works as expected

**Comment by haba713** [comment]
`./gradlew clean bootRun` requires that changed classes are compiled somehow. One option is to use Gradle  if IDE does not support automatic compilation: `./gradlew --continuous compileJava`.
