### ISSUE TITLE
Provide info about how to switch to other embedded Servers e.g Undertow - Improve documentation in general

### ISSUE THREAD

**Issue by masbaehr** [vaadin/base-starter-spring-gradle#2]
Hi, I can't find information about how to switch to other SpringBoot embedded Servers like Undertow or Jetty. This could be a reasonable first step to improve the documentation

**Comment by miguelatvaadin** [comment]
Thanks for the info, @masbaehr . 

Anyway, I would say this is not a Vaadin related issue, as this information is already inside the Springboot documentation (https://docs.spring.io/spring-boot/docs/2.4.5/reference/html/howto.html#howto-embedded-web-servers), so I close this issue.
