### ISSUE TITLE
Support of local npm installation and npm repository behind proxy

### ISSUE THREAD

**Issue by bbajor** [vaadin/base-starter-spring-gradle#3]
Hello, is it possible to use this plugin with a local npm installation and an npm-repository behind a proxy?

**Comment by miguelatvaadin** [comment]
Thanks for your question, @bbajor.

that should not be a problem. Anyway, could you please provide more details on what you intend to do? 

Best regards

**Comment by miguelatvaadin** [comment]
I will close this issue as no answer since April, 16. Please feel free to post a comment or reopen it if there is new info

**Comment by rbrki07** [comment]
@miguelatvaadin I would like to re-open this issue, because I just came across this requirement. If I try to build a Vaadin project based on this starter behind a corporate proxy, it won't be able to download the NodeJS installer from the internet and will therefor fail to build.

**Comment by mcollovati** [comment]
@rbrki07 did you already check https://vaadin.com/docs/latest/flow/configuration/development-mode/node-js#proxy-settings-for-downloading-frontend-toolchain?

**Comment by rbrki07** [comment]
Perfect :) Thank you @mcollovati 👍
