### ISSUE TITLE
Live reload stopped working in v14.4.x

### ISSUE THREAD

**Issue by gigi** [vaadin/base-starter-spring-gradle#5]
Hi!

Livereload widget is not working for Vaadin 14.4.x

If you change version https://github.com/vaadin/base-starter-spring-gradle/blob/v14/build.gradle#L19	to `set('vaadinVersion', "14.4.2")` livereload widget disappears although visible in the DOM.

Removing `webpack.generated.js` and `gradle vaadinClean && gradle vaadinPrepareFrontend` didn't help.

<img width="809" alt="vaadin-issue-3" src="https://user-images.githubusercontent.com/8811270/97750154-f0da9300-1af8-11eb-9b67-4b384e70294a.png">

Related thread
https://vaadin.com/forum/thread/18456179/live-reload-trouble-with-14-4

**Comment by pleku** [comment]
> Fixed in Gradle plugin 0.14.5.1
