### ISSUE TITLE
DevMode Gizmo went missing for Vaadin 14.4 and 14.5

### ISSUE THREAD

**Issue by enver-haase** [vaadin/base-starter-spring-gradle#7]
Probably has to do with
https://github.com/vaadin/base-starter-spring-gradle/issues/5

I suppose the Gradle Plugin needs to be updated to cater for the new location of the DevMode Gizmo.
("one change in 14.4 vs 14.3 is that the live reload widget is in a separate Webpack bundle")

https://vaadin.com/forum/thread/18456179/live-reload-trouble-with-14-4

**Comment by pleku** [comment]
> Fixed in Gradle plugin 0.14.5.1
